config/routes.rb
Rails.application.routes.draw do

  root 'homepage#index'
  resources :posts do
    resources :likes
  end
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :likes
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << :name
  devise_parameter_sanitizer.for(:account_update) << :name
end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new
    @like.user = current_user
    @like.post = @post

    if @like.save
      respond_to do |format|
        format.html { redirect_to @post, notice: "You have liked this post!" }
        format.json { render json: { likes: @post.likes.count } }
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, alert: "Like it!" }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :image )
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  #before_action :logged_in_user

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    #@posts = Post.all
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
    else
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def header(text)
  content_for(:header) { text.to_s }
end

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/homepage/_signup.html.erb
<div align="center" class="forma">

<% header "Sign Up" %>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
    <% if @validatable %>
      <span class="help-block"><%= @minimum_password_length %> characters minimum</span>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
  </div>

  <%= f.submit "Sign up", class: 'btn btn-primary' %>
<% end %>

<%= render "devise/shared/links" %>

</div>

app/views/homepage/index.html.erb
<% content_for :top_content do %>

<div class="col-md-8 col-md-offset-2">
  <div align="center"><%= image_tag "Voyage.png", class: "logo"%></div>
  <p align="center" class="intro-text">
    <em>"Travel does the heart good."</em>
    <br>
    <em>"Created by: Mimammaar"</em>
    <br>
    <span> <%= image_tag "Circled Chevron Down-64.png", class: "circle"%></span>
  </p>


</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= image_tag "sunset-plane.png", class: "video"%></div>
    <div class="col-xs-4">
      <%= image_tag "travel.gif", class: "video"%></div>
    <div class="col-xs-4">
      <%= image_tag "travel-industry-air.jpg", class: "video"%></div>
  </div>
</div>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voyage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    $(document).ready(function () {
    var Transitions = [];
    var TransitionEvents = [];
    var $bg = $("#bg");

    Transitions.push(new $.SParallax.Transition("top", 0, -50, "px", $bg, 0, 2));
    $.SParallax(Transitions, TransitionEvents);
  });
</script>

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= render "partials/navigation" %>  

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>



<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>



</body>
</html>

app/views/likes/_form.html.erb
<%= form_for([post, Like.new]) do |f| %>
  <%= f.submit "♥" %>
<% end %>

app/views/likes/index.html.erb
<center>
  <h1> Can't like this tadada dada dada can't like this <br> Stop Hammer Time!</h1>
<%= image_tag "hammer.gif" %>
</center>

app/views/partials/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <span><%= image_tag "Prop Plane-48.png", class: "light"%></span>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <%= link_to "Main", root_path, class: "page-scroll" %>
                </li>

                <% if user_signed_in? %>
                  <li><%=link_to "My profile", user_path(current_user), class: "page-scroll" %></li>
                  <li><%=link_to " Add a post", new_post_path(current_user), class: "page-scroll" %></li>
                  <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "page-scroll" %></li>
                <% else %>
                  <li><%= link_to "Create an Account", new_user_registration_path, class: "page-scroll" %></li>
                  <li><%= link_to "Log In", new_user_session_path, class: "page-scroll" %></li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/partials/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <!--<a href="<%= following_user_path(@user) %>">-->
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <!--<a href="<%= followers_user_path(@user) %>">-->
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <p><%= post.body %></p>
  <noscript>
    <%= render "/likes/form", post: post %>
  </noscript>
  <span class="counter" id="post-counter-<%= post.id %>">
    <%= post.likes.count %>
  </span>
  <%= link_to "♥", post_likes_path(post), class: "like-button", data: { post_id: post.id } %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Image</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.body %></td>
        <td><%= post.image %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<%# unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<%# end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="header">
    <h1>Edit User</h1>
  </div>

  <%= form_for(@user) do |f| %>

  <div>
  <p><%= f.label :first_name %></p>
  <%= f.text_field :first_name %></p>
  </div>

  <div>
  <p><%= f.label :last_name %></p>
  <%= f.text_field :last_name %></p>
  </div>

  <div>
  <p><%= f.label :email %></p>
  <%= f.text_field :email %></p>
  </div>

  <div>
  <p><%= f.label :password %></p>
  <%= f.text_field :password %></p>
  </div>

  <div>
  <%= f.submit "Save" %>
  </div>

  <% end %>


  <%= link_to "Back", @user %>
</div>

app/views/users/index.html.erb
<h2>All Users</h2>

  <% @users.each do |user| %>
    <h2><%= user.first_name %> <%= user.last_name %></h2>
    <p><%= user.email %></p>
    <p><%= user.password %></p>
    <p class="btn btn-default" role="button"><%= link_to "View details >", user %></p>
  <% end %>

app/views/users/show.html.erb
<div class="container">
  <h1>Profile</h1>
  <p><strong>Name:</strong> <%= @user.first_name %> <%= @user.last_name %></p>
  <p><strong>E-mail address:</strong> <%= @user.email %></p>
</div>

<div class="container">
  <h2>Stats</h2>
  <section class="stats">
    <%= render 'partials/stats' %>
  </section>
  <%= render 'follow_form' if user_signed_in? %>
</div>

<br />

<div class="navigation">
  <div class="container">
    <%= link_to "Back", users_path %> |
    <%= link_to "Edit", edit_user_path(@user) %>
  </div>
</div>


<div class="col-md-8">
  <% if @user.posts.any? %>
    <h3>Posts (<%= @user.posts.count %>)</h3>
    <ol class="posts">
      <%= render @posts %>
    </ol>
  <% end %>